spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.232.83:3306/studentsystem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Huangkai122@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.hk: debug
  file: log/blog-dev.log



